### ISSUE TITLE
Ignore Draft versions of Freshdesk Articles

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/StreamStats#807]
Recently we had a draft article, never published, that showed up in the news feed.
If possible, we should ignore artcles in 'draft' form, and only show published articles in freshdesk.

**Comment by kjacobsen16** [comment]
done

**Comment by HansVraga** [comment]
@kjacobsen16 I'm still seeing a draft article in Prod. I created an article and never published and it's in the Interface - screenshots below:

![image](https://user-images.githubusercontent.com/12058013/38929352-fd3451b2-42d9-11e8-8350-ae83f2e78e77.png)

![image](https://user-images.githubusercontent.com/12058013/38929312-decc3c44-42d9-11e8-8787-f0b806d34a32.png)

**Comment by HansVraga** [comment]
Maybe these changes didn't make it into Prod with the push?

**Comment by kjacobsen16** [comment]
Yeah, looks like they didn't get pushed to the prod s3, just the test s3.
